### ISSUE TITLE
Not supported on Windows

### ISSUE THREAD

**Issue by annapankiewicz** [drewwalters96/subber#31]
Subber does not support Windows, and this should be reflected in its documentation.

When running Subber as a Python package on Windows, starting the REST API with Gunicorn fails and gives "ModuleNotFoundError: No module named 'fcntl'".

**Comment by drewwalters96** [comment]
Thank you for the contribution @annapankiewicz! This definitely should be made clear in the documentation; we will address this.

Note: this issue applies to developers looking to run Subber as a python package, so it should probably be added to that section. Running Subber as a container is still supported on windows.

**Comment by drewwalters96** [comment]
Closed in #35
