### ISSUE TITLE
Load config in subber.py

### ISSUE THREAD

**Issue by drewwalters96** [drewwalters96/subber#42]
Thank you for your contribution to Subber! Please fill out one of the two templates below (issue or feature request).

### Feature request (please include as much detail as possible):

The config file should be loaded in `subber.py` and rather than doing so directly from the Reddit class in `reddit.py`.

This addresses the confusing import system for the unit tests in #41

**Comment by danieledwardknudsen** [comment]
Can you clarify how this should affect #41 ? @annapankiewicz  @drewwalters96

**Comment by drewwalters96** [comment]
@danieledwardknudsen This does not affect #41 directly at this time. This issue is filed in response to difficulties encountered in #41 and prevents reloading the config file multiple times whenever it is needed during runtime.

The solution is to load it once at startup.
