### ISSUE TITLE
Check that the username passed to the API exists

### ISSUE THREAD

**Issue by danieledwardknudsen** [drewwalters96/subber#9]
If the username passed to the API is invalid, handle the error and respond appropriately

**Comment by ghost** [comment]
what're you thinking for a solution to this? just pinging reddit.com/user/{username} and making sure there's no 404 error?

**Comment by drewwalters96** [comment]
PRAW actually has [exceptions](http://praw.readthedocs.io/en/v3.6.1/pages/exceptions.html) that are thrown when trying to access a bad resource.

As far as the API response for that goes, that is not _as_ important, but a username is also bad for us if a user has no posts or comments. It would be nice to also handle that API response in this issue as well.

**Comment by drewwalters96** [comment]
Closed in #41
